CREATE TABLE IF NOT EXISTS `users`
(
    `id`            BIGINT   NOT NULL AUTO_INCREMENT,
    `created`       DATETIME NOT NULL,
    CONSTRAINT `pk` PRIMARY KEY (`id`)
) ENGINE = INNODB
  CHARSET = UTF8MB4
  COLLATE = UTF8MB4_UNICODE_CI
